title: Blog of wild people
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Главная
   url: /index.html
 - title: О сайте
   url: /about
 - title: Контакты
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
